name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install && composer update && composer install

      - name: Build assets
        run: npm run production

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.SERVER }}
          remote_user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'public/'
          target: '/var/www/pokemon-tcg/'
